org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.newDsl=false
android.builtInKotlin=false

# Fix multi-drive root issue on Windows (C: pub cache vs D: project)
kotlin.incremental=false
kotlin.incremental.android=false
org.gradle.configuration-cache=false
